### ISSUE TITLE
Error after updating config

### ISSUE THREAD

**Issue by rgerr** [RobXYZ/homebridge-brunt#1]
Hi,

First of all, thank you for this plug-in!

Having an issue after updating the config with the provided info:

/usr/lib/node_modules/homebridge-brunt/lib/bruntapi.js:76
		    if (callback) callback(str);
                    ^
TypeError: Cannot read property 'sessionId' of undefined
    at /usr/lib/node_modules/homebridge-brunt/index.js:51:29
    at /usr/lib/node_modules/homebridge-brunt/lib/bruntapi.js:137:5
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-brunt/lib/bruntapi.js:76:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Could you possibly help me sort this out?

**Comment by rgerr** [comment]
Fixed it by installing it via sudo npm install -g homebridge-brunt —unsafe-perm and using the e-mail adress instead of username under “user”.
