### ISSUE TITLE
Wrong state after changing position manually. 

### ISSUE THREAD

**Issue by Char1ei** [RobXYZ/homebridge-brunt#2]
After I change curtain position via click button on brunt engine, brunt in Home app shows trying to get previous requested position from the Home app instead of current position.

**Comment by RobXYZ** [comment]
This seems to be a problem with the Brunt API, it does not update the position when the button has been pressed. I find the same problem when using the Alexa skill. If the blind has been opened with the button I need to ask Alexa to open it first before closing it again.

**Comment by LPFchan** [comment]
```
[브런트 블라인드 엔진@@Target Position] characteristic was supplied illegal value: number 111 exceeded maximum of 100
[26/09/2022, 21:10:11] [homebridge-brunt] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 111 exceeded maximum of 100. See https://homebridge.io/w/JtMGR for more info.
[26/09/2022, 21:10:11] [homebridge-brunt] Error: 
    at TargetPosition.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at TargetPosition.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2049:14)
    at /var/lib/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1617:24
    at /var/lib/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at TargetPosition.<anonymous> (/var/lib/homebridge/node_modules/homebridge-brunt/accessories/things.js:88:4)
    at TargetPosition.emit (node:events:513:28)
    at /var/lib/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at TargetPosition.<anonymous> (/var/lib/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/var/lib/homebridge/node_modules/hap-nodejs/node_modules/tslib/tslib.js:144:27)
```

I think I'm having a same problem.
