### ISSUE TITLE
Change in API

### ISSUE THREAD

**Issue by rgerr** [RobXYZ/homebridge-brunt#6]
Hi there,

Just got this error message after restarting Homebridge:

[6/1/2019, 8:42:47 PM] TypeError: Cannot read property 'sessionId' of undefined
    at /usr/lib/node_modules/homebridge-brunt/index.js:51:30
    at /usr/lib/node_modules/homebridge-brunt/lib/bruntapi.js:137:5
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-brunt/lib/bruntapi.js:76:21)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I think the API might have been changed, any ideas on this?

**Comment by rgerr** [comment]
Reinstalled the plug-in, same error after updating the config.

**Comment by simplenotezy** [comment]
OK, so why is this issue closed? 😊
